name: flutter_mvvm_boilerplate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter

# flutter pub upgrade --major-versions : to remove conflicts
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.4

  ## dev- dependencies
  stacked: ^2.2.8
  logger: 1.1.0
  intl: 0.17.0
  stacked_services: ^0.8.16
  hooks_riverpod: 1.0.3
  # get: ^4.6.3
  shared_preferences: ^2.0.13
  json_annotation: ^4.4.0
  dropdown_button2: ^1.2.2

  #network
  alice: 0.2.5
  http: 0.13.4
  url_launcher: ^6.0.18
  path_provider: ^2.0.8
  http_interceptor: 1.0.2

  #UI
  google_fonts: ^2.3.2
  introduction_screen: ^3.0.2
  cached_network_image: 3.2.0
  image_picker: ^0.8.5+3
  webview_flutter: ^3.0.0
  navigation_history_observer: 1.1.0
  package_info_plus: ^1.4.2

  # firebase
  # firebase_core: ^1.12.0
  # firebase_storage: ^10.2.8
  # cloud_firestore: ^3.1.9
  # firebase_crashlytics: ^2.5.1
  firebase_auth: ^3.3.6
  # firebase_messaging: ^11.2.6
  # firebase_analytics: ^9.1.0

  # socials 
  youtube_player_flutter: 8.0.0
  google_sign_in: ^5.2.3
  launch_review: 3.0.1
  pull_to_refresh: ^2.0.0
  share_plus: ^4.0.4
  dart_jsonwebtoken: ^2.4.1
  corsac_jwt: ^1.0.0-nullsafety.1
  speech_to_text: ^5.4.3
  status_bar_control: ^3.2.1
  shimmer: ^2.0.0
  file_picker: ^4.4.0
  pinput: ^2.2.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  build_test:
  stacked_generator:
  freezed: ^1.1.0
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  # flutter_mobile_vision: 0.1.4+1

  flutter_native_splash: ^2.1.6

    # run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/



